# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8090
  port: 8091
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 30

# Spring配置
spring:
  application:
    name: iot

  profiles:
    active: dev

  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

  # redis 配置
  redis:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10S
        time-between-eviction-runs: 1S


app:
  font-url: https://www.baidu.com/
  description: @project.description@

  oss:
    access-key-id:
    access-key-secret:
    bucket-name:

  tenant:
    enable: true
    tables: [sys_corp_info, sys_dict_data, sys_file_mapping, sys_menu_info, sys_user_role,
             sys_role_menu, t_iot_protocol_config, t_iot_protocol_jar
             t_sink_property_defin, t_sink_property_log, t_sink_task_info_log,
             t_sink_thing_model_message, sys_oauth_client]
